# coding: utf-8

# flake8: noqa

"""
    Digiseg API

    ### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" />  ## Audience taxonomy  Digiseg audiences are grouped into private and business audiences. In each group there are categories that then contain the audiences. The API endpoints that communicate audiences and household characteristics, audience codes are being used.  The following table can be used as a reference for audience codes. Note that Digiseg will at times update names of audiences for purposes of internationalization, clarity or other such purposes - but the codes will remain as-is and should be considered a stable point of reference for the audience.  ### Core audiences | Group | Category code | Audience Code | Category name | Audience Name | |-------|---------------|---------------|---------------|---------------| |  private  |  home_type  |  a1  |  Home Type  |  Apartment  | |    |    |  a2  |  Home Type  |  House  | |    |  savings  |  b1  |  Savings  |  No Savings  | |    |    |  b2  |  Savings  |  Smaller Savings  | |    |    |  b3  |  Savings  |  Larger Savings  | |    |  lifecycle  |  c1  |  Lifecycle  |  Young couples and singles  | |    |    |  c2  |  Lifecycle  |  Early family life  | |    |    |  c3  |  Lifecycle  |  Middle-aged families  | |    |    |  c4  |  Lifecycle  |  Mature families  | |    |    |  c5  |  Lifecycle  |  Pensioners / Retirees  | |    |  cars  |  d1  |  Cars in Household  |  No cars  | |    |    |  d2  |  Cars in Household  |  1 car  | |    |    |  d3  |  Cars in Household  |  2 or more cars  | |    |  children  |  e1  |  Children in the Household  |  No children  | |    |    |  e2  |  Children in the Household  |  1 child  | |    |    |  e3  |  Children in the Household  |  2 or more children  | |    |  education  |  f1  |  Education  |  Basic  | |    |    |  f2  |  Education  |  Medium  | |    |    |  f3  |  Education  |  Higher  | |    |  neighbourhood_type  |  g1  |  Neighbourhood Type  |  Countryside  | |    |    |  g2  |  Neighbourhood Type  |  Village  | |    |    |  g3  |  Neighbourhood Type  |  Suburban  | |    |    |  g4  |  Neighbourhood Type  |  City  | |    |  income  |  h1  |  Household Income  |  Lowest 20%  | |    |    |  h2  |  Household Income  |  Lowest 20-40%  | |    |    |  h3  |  Household Income  |  Middle 40-60%  | |    |    |  h4  |  Household Income  |  Highest 60-80%  | |    |    |  h5  |  Household Income  |  Top 20%  | |    |  home_ownership  |  j1  |  Home Ownership  |  Rent  | |    |    |  j2  |  Home Ownership  |  Own  | |    |  building_age  |  k1  |  Building Age  |  Pre 1945  | |    |    |  k2  |  Building Age  |  1945-1989  | |    |    |  k3  |  Building Age  |  1990 until today  | |    |  living_space  |  l1  |  Living space  |  Small  | |    |    |  l2  |  Living space  |  Medium  | |    |    |  l3  |  Living space  |  Large  | |    |  tech_level  |  n1  |  Tech-Level in Household  |  Basic  | |    |    |  n2  |  Tech-Level in Household  |  Medium  | |    |    |  n3  |  Tech-Level in Household  |  High  | |  business  |  size  |  ba1  |  Business  |  Small Business  | |    |    |  ba2  |  Business  |  Medium Business  | |    |    |  ba3  |  Business  |  Larger Business  | ### Composite audiences | Category code | Audience Code | Category name | Audience Name | |---------------|---------------|---------------|---------------| |  composite_betting  |  060  |  Betting Online  |  Betting, Casino & Poker  | |  composite_buyingpower  |  092  |  Buying Power  |  Buying Power Low  | |    |  093  |  Buying Power  |  Buying Power High  | |  composite_carclass  |  001  |  Car Classes  |  Micro & City  | |    |  002  |  Car Classes  |  Mini  | |    |  003  |  Car Classes  |  Small Medium / Compact  | |    |  004  |  Car Classes  |  Large Medium  | |    |  005  |  Car Classes  |  Large Premium  | |    |  006  |  Car Classes  |  Large Luxury Sedan  | |    |  007  |  Car Classes  |  MPV / Minivans  | |    |  008  |  Car Classes  |  SUV  | |    |  009  |  Car Classes  |  Electric & Hybrid  | |    |  010  |  Car Classes  |  Sport  | |  composite_career  |  110  |  Recruitment & Career  |  Employment in Large Companies  | |    |  111  |  Recruitment & Career  |  C-Level Positions  | |    |  112  |  Recruitment & Career  |  Management Positions  | |    |  113  |  Recruitment & Career  |  Graduate Programs & First Job  | |    |  114  |  Recruitment & Career  |  IT Positions  | |    |  158  |  Recruitment & Career  |  Employment in Small Companies  | |  composite_carservice  |  011  |  Car Services  |  Service & Car Parts  | |    |  012  |  Car Services  |  Car Tires  | |    |  013  |  Car Services  |  Car Leasing (Private)  | |  composite_childrensarticles  |  044  |  Children Articles  |  Games & Toys  | |  composite_computer_games  |  059  |  Computer Games  |  Games & Consoles  | |  composite_culture_entertainment  |  045  |  Culture & Entertainment  |  Cinema Tickets  | |    |  046  |  Culture & Entertainment  |  Opera & Theater  | |    |  047  |  Culture & Entertainment  |  Concert & Festival  | |    |  048  |  Culture & Entertainment  |  Museum & Exhibition  | |    |  049  |  Culture & Entertainment  |  Books  | |    |  050  |  Culture & Entertainment  |  Audiobooks  | |  composite_electronics  |  061  |  Electronics  |  TV  | |    |  062  |  Electronics  |  Phones & Smartphones  | |    |  063  |  Electronics  |  Small Domestic Appliances  | |    |  064  |  Electronics  |  Major Domestic Appliances  | |    |  065  |  Electronics  |  Garden Articles  | |    |  066  |  Electronics  |  HiFi Audio  | |    |  067  |  Electronics  |  Computer Tablet  | |    |  068  |  Electronics  |  Software & Apps  | |  composite_fashion  |  130  |  Fashion & Shopping  |  Shopping Mall Visitors  | |    |  131  |  Fashion & Shopping  |  Footwear & Shoes  | |    |  132  |  Fashion & Shopping  |  Jewellery  | |    |  133  |  Fashion & Shopping  |  Clothes  | |  composite_financials  |  014  |  Banking / Financing  |  House Loan  | |    |  015  |  Banking / Financing  |  Car Loan  | |    |  016  |  Banking / Financing  |  Consumer Loan  | |    |  017  |  Banking / Financing  |  Renovation  | |    |  018  |  Banking / Financing  |  Quick Loan  | |    |  019  |  Banking / Financing  |  Mobile Banking  | |    |  020  |  Banking / Financing  |  Investors  | |  composite_fmcg  |  069  |  Fast-Moving Consumer Good (FMCG)  |  Candy & Sweets  | |    |  070  |  Fast-Moving Consumer Good (FMCG)  |  Energy Drinks  | |    |  071  |  Fast-Moving Consumer Good (FMCG)  |  Sodas  | |    |  072  |  Fast-Moving Consumer Good (FMCG)  |  Chips  | |    |  073  |  Fast-Moving Consumer Good (FMCG)  |  Washing Detergents  | |    |  074  |  Fast-Moving Consumer Good (FMCG)  |  Bio & Organic Products  | |    |  075  |  Fast-Moving Consumer Good (FMCG)  |  Baby Food  | |    |  076  |  Fast-Moving Consumer Good (FMCG)  |  Dairy Products  | |    |  077  |  Fast-Moving Consumer Good (FMCG)  |  Beer  | |  composite_homerenovation  |  031  |  Home Renovation  |  House or apartment decoration  | |    |  032  |  Home Renovation  |  Kitchen  | |    |  033  |  Home Renovation  |  Bathroom & Plumbing  | |    |  034  |  Home Renovation  |  Windows, Doors & Tiles  | |    |  035  |  Home Renovation  |  Garden  | |    |  036  |  Home Renovation  |  Furniture  | |  composite_homesecurity  |  094  |  Home Security  |  House Alarms & Video Surveillance  | |  composite_insurance  |  021  |  Insurance  |  Car  | |    |  022  |  Insurance  |  House & Apartment  | |    |  023  |  Insurance  |  Accident Insurance  | |    |  024  |  Insurance  |  Life Insurance  | |    |  025  |  Insurance  |  Pension Fund  | |    |  026  |  Insurance  |  Travel Insurance  | |  composite_lifecycle  |  083  |  Lifestyle  |  Fitness, Gym & Workout  | |    |  084  |  Lifestyle  |  Stop Smoking  | |    |  085  |  Lifestyle  |  Natural Medicin  | |    |  086  |  Lifestyle  |  Gym Supplements & Nutrients  | |    |  087  |  Lifestyle  |  Small Pets  | |    |  088  |  Lifestyle  |  Large Pets  | |    |  089  |  Lifestyle  |  Weight Loss  | |    |  091  |  Lifestyle  |  Students  | |  composite_occasions  |  102  |  Occasions & Presents  |  Valentine's Day  | |    |  103  |  Occasions & Presents  |  Mothers's Day  | |    |  104  |  Occasions & Presents  |  Fathers's Day  | |    |  105  |  Occasions & Presents  |  Children's Day  | |    |  106  |  Occasions & Presents  |  Wedding & Engagement  | |    |  107  |  Occasions & Presents  |  Women's Day  | |    |  108  |  Occasions & Presents  |  Black Friday  | |    |  109  |  Occasions & Presents  |  Cyber Monday  | |    |  152  |  Occasions & Presents  |  Presents for young / inexpensive  | |    |  153  |  Occasions & Presents  |  Presents for young / expensive  | |    |  154  |  Occasions & Presents  |  Presents for families with children / inexpensive  | |    |  155  |  Occasions & Presents  |  Presents for families with children / expensive  | |    |  156  |  Occasions & Presents  |  Presents for mature / inexpensive  | |    |  157  |  Occasions & Presents  |  Presents for mature / expensive  | |  composite_olympics  |  159  |  Olympics  |  Olympics Visitors  | |    |  160  |  Olympics  |  Olympics Watchers  | |  composite_personalhygiene  |  078  |  Personal Hygiene  |  Baby Hygiene  | |    |  079  |  Personal Hygiene  |  SPF Sunscreen  | |    |  080  |  Personal Hygiene  |  Toothbrushes & Toothpaste  | |    |  081  |  Personal Hygiene  |  Cosmetics  | |    |  082  |  Personal Hygiene  |  Parfumes  | |  composite_politics  |  115  |  Political Themes  |  Children & Youth  | |    |  116  |  Political Themes  |  Elder Care  | |    |  117  |  Political Themes  |  Research & Education System  | |    |  118  |  Political Themes  |  Public Transport  | |    |  119  |  Political Themes  |  Car Transport & Road Infrastructure  | |    |  120  |  Political Themes  |  Art & Culture  | |    |  121  |  Political Themes  |  Green Transition & Environment  | |    |  122  |  Political Themes  |  Law & Order  | |    |  123  |  Political Themes  |  Immigration  | |    |  124  |  Political Themes  |  Tax Reliefs  | |    |  126  |  Political Themes  |  Euro-supporters  | |    |  128  |  Political Themes  |  Women's Rights & Gender Equality  | |    |  129  |  Political Themes  |  Corruption & Bureaucracy  | |  composite_realestatetrading  |  027  |  Real Estate Trading  |  First-time Buyers  | |    |  028  |  Real Estate Trading  |  Summerhouse  | |    |  029  |  Real Estate Trading  |  Apartment  | |    |  030  |  Real Estate Trading  |  House & Villa  | |  composite_restaurants  |  037  |  Restaurants  |  Fastfood  | |    |  038  |  Restaurants  |  Restaurant  | |    |  039  |  Restaurants  |  Cafe & Bar  | |  composite_telecom  |  040  |  Telecommunication  |  Internet  | |    |  041  |  Telecommunication  |  Mobile Phone Subscription  | |    |  042  |  Telecommunication  |  Satellite TV  | |    |  043  |  Telecommunication  |  Streaming Services  | |  composite_travel  |  051  |  Travel & Vacation  |  Airplane Tickets  | |    |  052  |  Travel & Vacation  |  Business Travelers  | |    |  053  |  Travel & Vacation  |  Car Vacation  | |    |  054  |  Travel & Vacation  |  All Inclusive / Resorts  | |    |  055  |  Travel & Vacation  |  Adventure  | |    |  056  |  Travel & Vacation  |  Luxury  | |    |  057  |  Travel & Vacation  |  City Break  | |    |  058  |  Travel & Vacation  |  Hotels  | |  composite_winter  |  134  |  Christmas & Winter  |  Christmas Gifts - Young people | Over 100 €  | |    |  135  |  Christmas & Winter  |  Christmas Gifts - Young people | Under 100 €  | |    |  136  |  Christmas & Winter  |  Christmas Gifts | Families with children | Over 100 €  | |    |  137  |  Christmas & Winter  |  Christmas Gifts | Families with children | Under 100 €  | |    |  138  |  Christmas & Winter  |  Christmas Gifts | 50+ | Over 100 €  | |    |  139  |  Christmas & Winter  |  Christmas Gifts | 50+ | Under 100 €  | |    |  140  |  Christmas & Winter  |  Personal Gifts | Online Photo Books & Calendars  | |    |  141  |  Christmas & Winter  |  Winter Outerwear | Over 250 €  | |    |  142  |  Christmas & Winter  |  Winter Outerwear | Under 250 €  | |    |  143  |  Christmas & Winter  |  Winter Outerwear for Children  | |    |  144  |  Christmas & Winter  |  Winter Sports Clothing & Gear  | |    |  145  |  Christmas & Winter  |  Decoration | House & Garden  | |    |  146  |  Christmas & Winter  |  Decoration | Apartment & Balcony  | |    |  147  |  Christmas & Winter  |  Food and Wine | Online Supermarket w. Delivery  | |    |  148  |  Christmas & Winter  |  Food and Wine | Online Store  | |    |  149  |  Christmas & Winter  |  Fireplace & Wood Burning Stove  | |    |  151  |  Christmas & Winter  |  Winter to Summer Tire Change  |  There is also an interactive [Audience builder](https://digiseg.io/cookieless-audience-builder/) which lets you discover the targeting reach and power of combining various household characteristics into composite audiences. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@digiseg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from digiseg_api.api.accounts_api import AccountsApi
from digiseg_api.api.audiences_api import AudiencesApi
from digiseg_api.api.auth_api import AuthApi
from digiseg_api.api.measurement_clients_api import MeasurementClientsApi
from digiseg_api.api.measurement_labels_api import MeasurementLabelsApi
from digiseg_api.api.populations_api import PopulationsApi
from digiseg_api.api.studies_api import StudiesApi
from digiseg_api.api.subscriptions_api import SubscriptionsApi
from digiseg_api.api.usage_api import UsageApi
from digiseg_api.api.users_api import UsersApi

# import ApiClient
from digiseg_api.api_response import ApiResponse
from digiseg_api.api_client import ApiClient
from digiseg_api.configuration import Configuration
from digiseg_api.exceptions import OpenApiException
from digiseg_api.exceptions import ApiTypeError
from digiseg_api.exceptions import ApiValueError
from digiseg_api.exceptions import ApiKeyError
from digiseg_api.exceptions import ApiAttributeError
from digiseg_api.exceptions import ApiException

# import models into sdk package
from digiseg_api.models.access_token_data import AccessTokenData
from digiseg_api.models.account_aux import AccountAux
from digiseg_api.models.account_base import AccountBase
from digiseg_api.models.account_creation import AccountCreation
from digiseg_api.models.account_creation_aux import AccountCreationAux
from digiseg_api.models.account_full import AccountFull
from digiseg_api.models.account_include_aux import AccountIncludeAux
from digiseg_api.models.account_include_param import AccountIncludeParam
from digiseg_api.models.account_item import AccountItem
from digiseg_api.models.account_links import AccountLinks
from digiseg_api.models.account_mutation import AccountMutation
from digiseg_api.models.account_mutation_aux import AccountMutationAux
from digiseg_api.models.account_owner_creation import AccountOwnerCreation
from digiseg_api.models.account_sort_option import AccountSortOption
from digiseg_api.models.account_stripe_billing_info import AccountStripeBillingInfo
from digiseg_api.models.account_subscription_base import AccountSubscriptionBase
from digiseg_api.models.account_subscription_creation import AccountSubscriptionCreation
from digiseg_api.models.account_subscription_full import AccountSubscriptionFull
from digiseg_api.models.account_subscription_full_aux import AccountSubscriptionFullAux
from digiseg_api.models.account_subscription_item import AccountSubscriptionItem
from digiseg_api.models.account_subscription_item_aux import AccountSubscriptionItemAux
from digiseg_api.models.account_subscription_payment_configuration import AccountSubscriptionPaymentConfiguration
from digiseg_api.models.account_subscriptions_summary import AccountSubscriptionsSummary
from digiseg_api.models.account_user_addition import AccountUserAddition
from digiseg_api.models.add_user_to_account201_response import AddUserToAccount201Response
from digiseg_api.models.api_key_aux import ApiKeyAux
from digiseg_api.models.api_key_base import ApiKeyBase
from digiseg_api.models.api_key_creation import ApiKeyCreation
from digiseg_api.models.api_key_full import ApiKeyFull
from digiseg_api.models.api_key_full_with_token import ApiKeyFullWithToken
from digiseg_api.models.api_key_item import ApiKeyItem
from digiseg_api.models.api_key_links import ApiKeyLinks
from digiseg_api.models.api_key_mutation import ApiKeyMutation
from digiseg_api.models.api_key_status import ApiKeyStatus
from digiseg_api.models.api_key_token import ApiKeyToken
from digiseg_api.models.audience import Audience
from digiseg_api.models.audience_category_stats import AudienceCategoryStats
from digiseg_api.models.audience_data_daily_usage import AudienceDataDailyUsage
from digiseg_api.models.audience_data_monthly_usage import AudienceDataMonthlyUsage
from digiseg_api.models.audience_data_realtime_usage import AudienceDataRealtimeUsage
from digiseg_api.models.audience_data_usage import AudienceDataUsage
from digiseg_api.models.audience_example_input import AudienceExampleInput
from digiseg_api.models.audience_example_inputs_response import AudienceExampleInputsResponse
from digiseg_api.models.audience_response import AudienceResponse
from digiseg_api.models.audience_response_status import AudienceResponseStatus
from digiseg_api.models.audience_stats import AudienceStats
from digiseg_api.models.audiences_include_param import AudiencesIncludeParam
from digiseg_api.models.auth_token_request import AuthTokenRequest
from digiseg_api.models.auth_token_response import AuthTokenResponse
from digiseg_api.models.business_audience_stats import BusinessAudienceStats
from digiseg_api.models.business_audience_stats_audience_categories import BusinessAudienceStatsAudienceCategories
from digiseg_api.models.category_populations_full import CategoryPopulationsFull
from digiseg_api.models.company_size import CompanySize
from digiseg_api.models.company_type import CompanyType
from digiseg_api.models.comparison import Comparison
from digiseg_api.models.comparisons_container import ComparisonsContainer
from digiseg_api.models.country_stats import CountryStats
from digiseg_api.models.create_account201_response import CreateAccount201Response
from digiseg_api.models.create_api_key201_response import CreateApiKey201Response
from digiseg_api.models.create_measurement_client201_response import CreateMeasurementClient201Response
from digiseg_api.models.create_shared_report201_response import CreateSharedReport201Response
from digiseg_api.models.create_study201_response import CreateStudy201Response
from digiseg_api.models.customer_communication_message import CustomerCommunicationMessage
from digiseg_api.models.day_of_month_stats import DayOfMonthStats
from digiseg_api.models.day_of_week_stats import DayOfWeekStats
from digiseg_api.models.error_response import ErrorResponse
from digiseg_api.models.frequency_stats import FrequencyStats
from digiseg_api.models.get_account_subscription_by_id200_response import GetAccountSubscriptionById200Response
from digiseg_api.models.get_account_subscriptions200_response import GetAccountSubscriptions200Response
from digiseg_api.models.get_api_key_by_id200_response import GetApiKeyById200Response
from digiseg_api.models.get_popuplation_by_key200_response import GetPopuplationByKey200Response
from digiseg_api.models.get_user_account_membership200_response import GetUserAccountMembership200Response
from digiseg_api.models.hour_of_day_stats import HourOfDayStats
from digiseg_api.models.identifyable_object import IdentifyableObject
from digiseg_api.models.identifyable_object1 import IdentifyableObject1
from digiseg_api.models.limited_or_full_feature import LimitedOrFullFeature
from digiseg_api.models.list_api_keys_by_account_id200_response import ListApiKeysByAccountId200Response
from digiseg_api.models.list_audience_data_daily_usage200_response import ListAudienceDataDailyUsage200Response
from digiseg_api.models.list_audience_data_monthly_usage200_response import ListAudienceDataMonthlyUsage200Response
from digiseg_api.models.list_audience_data_realtime_usage200_response import ListAudienceDataRealtimeUsage200Response
from digiseg_api.models.list_measurement_clients200_response import ListMeasurementClients200Response
from digiseg_api.models.list_measurement_labels200_response import ListMeasurementLabels200Response
from digiseg_api.models.list_pagination_links import ListPaginationLinks
from digiseg_api.models.list_pagination_meta import ListPaginationMeta
from digiseg_api.models.list_pagination_meta_page import ListPaginationMetaPage
from digiseg_api.models.list_popuplations200_response import ListPopuplations200Response
from digiseg_api.models.list_shared_reports_by_study_id200_response import ListSharedReportsByStudyId200Response
from digiseg_api.models.list_studies200_response import ListStudies200Response
from digiseg_api.models.list_subscription_offers200_response import ListSubscriptionOffers200Response
from digiseg_api.models.list_subscription_plans200_response import ListSubscriptionPlans200Response
from digiseg_api.models.list_users_by_account_id200_response import ListUsersByAccountId200Response
from digiseg_api.models.measurement import Measurement
from digiseg_api.models.measurement_client_base import MeasurementClientBase
from digiseg_api.models.measurement_client_full import MeasurementClientFull
from digiseg_api.models.measurement_client_item import MeasurementClientItem
from digiseg_api.models.measurement_client_mutation import MeasurementClientMutation
from digiseg_api.models.measurement_event_link import MeasurementEventLink
from digiseg_api.models.measurement_event_link_parameter_info import MeasurementEventLinkParameterInfo
from digiseg_api.models.measurement_event_links import MeasurementEventLinks
from digiseg_api.models.measurement_event_set import MeasurementEventSet
from digiseg_api.models.measurement_integration_platform import MeasurementIntegrationPlatform
from digiseg_api.models.measurements_container import MeasurementsContainer
from digiseg_api.models.passwordless_auth_request import PasswordlessAuthRequest
from digiseg_api.models.permission_scopes import PermissionScopes
from digiseg_api.models.plan_feature_set import PlanFeatureSet
from digiseg_api.models.population_audience_category_set_business_section import PopulationAudienceCategorySetBusinessSection
from digiseg_api.models.population_audience_category_set_private_section import PopulationAudienceCategorySetPrivateSection
from digiseg_api.models.population_audience_category_set_section import PopulationAudienceCategorySetSection
from digiseg_api.models.population_full import PopulationFull
from digiseg_api.models.population_item import PopulationItem
from digiseg_api.models.population_source import PopulationSource
from digiseg_api.models.population_source_business_category_set import PopulationSourceBusinessCategorySet
from digiseg_api.models.population_source_business_category_set_size import PopulationSourceBusinessCategorySetSize
from digiseg_api.models.population_source_business_section import PopulationSourceBusinessSection
from digiseg_api.models.population_source_not_resolved_section import PopulationSourceNotResolvedSection
from digiseg_api.models.population_source_private_category_set import PopulationSourcePrivateCategorySet
from digiseg_api.models.population_source_private_category_set_building_age import PopulationSourcePrivateCategorySetBuildingAge
from digiseg_api.models.population_source_private_category_set_cars import PopulationSourcePrivateCategorySetCars
from digiseg_api.models.population_source_private_category_set_children import PopulationSourcePrivateCategorySetChildren
from digiseg_api.models.population_source_private_category_set_education import PopulationSourcePrivateCategorySetEducation
from digiseg_api.models.population_source_private_category_set_home_ownership import PopulationSourcePrivateCategorySetHomeOwnership
from digiseg_api.models.population_source_private_category_set_home_type import PopulationSourcePrivateCategorySetHomeType
from digiseg_api.models.population_source_private_category_set_income import PopulationSourcePrivateCategorySetIncome
from digiseg_api.models.population_source_private_category_set_lifecycle import PopulationSourcePrivateCategorySetLifecycle
from digiseg_api.models.population_source_private_category_set_living_space import PopulationSourcePrivateCategorySetLivingSpace
from digiseg_api.models.population_source_private_category_set_neighbourhood_type import PopulationSourcePrivateCategorySetNeighbourhoodType
from digiseg_api.models.population_source_private_category_set_savings import PopulationSourcePrivateCategorySetSavings
from digiseg_api.models.population_source_private_category_set_tech_level import PopulationSourcePrivateCategorySetTechLevel
from digiseg_api.models.population_source_private_section import PopulationSourcePrivateSection
from digiseg_api.models.postal_address import PostalAddress
from digiseg_api.models.private_audience_stats import PrivateAudienceStats
from digiseg_api.models.private_audience_stats_audience_categories import PrivateAudienceStatsAudienceCategories
from digiseg_api.models.query_study_audience_stats200_response import QueryStudyAudienceStats200Response
from digiseg_api.models.query_study_country_stats200_response import QueryStudyCountryStats200Response
from digiseg_api.models.query_study_device_stats200_response import QueryStudyDeviceStats200Response
from digiseg_api.models.query_study_frequency_stats200_response import QueryStudyFrequencyStats200Response
from digiseg_api.models.query_study_timeline_stats200_response import QueryStudyTimelineStats200Response
from digiseg_api.models.query_study_timing_stats200_response import QueryStudyTimingStats200Response
from digiseg_api.models.registration_by_id_response_data import RegistrationByIdResponseData
from digiseg_api.models.registration_creation_response_data import RegistrationCreationResponseData
from digiseg_api.models.registration_request import RegistrationRequest
from digiseg_api.models.registration_verification_response_data import RegistrationVerificationResponseData
from digiseg_api.models.registration_verification_response_links import RegistrationVerificationResponseLinks
from digiseg_api.models.resolve_audiences_of_multiple_request import ResolveAudiencesOfMultipleRequest
from digiseg_api.models.resolve_audiences_of_multiple_request_item import ResolveAudiencesOfMultipleRequestItem
from digiseg_api.models.resolve_audiences_of_multiple_response import ResolveAudiencesOfMultipleResponse
from digiseg_api.models.resolve_audiences_of_multiple_response_item import ResolveAudiencesOfMultipleResponseItem
from digiseg_api.models.resource_sharing_token_request import ResourceSharingTokenRequest
from digiseg_api.models.send_email_query import SendEmailQuery
from digiseg_api.models.send_email_user_filters import SendEmailUserFilters
from digiseg_api.models.shared_report_aux import SharedReportAux
from digiseg_api.models.shared_report_base import SharedReportBase
from digiseg_api.models.shared_report_creation import SharedReportCreation
from digiseg_api.models.shared_report_full import SharedReportFull
from digiseg_api.models.shared_report_item import SharedReportItem
from digiseg_api.models.shared_report_public_data import SharedReportPublicData
from digiseg_api.models.shared_report_type import SharedReportType
from digiseg_api.models.stripe_account_subscription_checkout_session import StripeAccountSubscriptionCheckoutSession
from digiseg_api.models.stripe_account_subscription_purchase_creation import StripeAccountSubscriptionPurchaseCreation
from digiseg_api.models.study_audience_stats import StudyAudienceStats
from digiseg_api.models.study_aux import StudyAux
from digiseg_api.models.study_base import StudyBase
from digiseg_api.models.study_country_stats import StudyCountryStats
from digiseg_api.models.study_creation import StudyCreation
from digiseg_api.models.study_creation_data import StudyCreationData
from digiseg_api.models.study_device_stats import StudyDeviceStats
from digiseg_api.models.study_device_sub_type_stats import StudyDeviceSubTypeStats
from digiseg_api.models.study_device_type_category import StudyDeviceTypeCategory
from digiseg_api.models.study_device_type_category_stats import StudyDeviceTypeCategoryStats
from digiseg_api.models.study_event_creation import StudyEventCreation
from digiseg_api.models.study_frequency_stats import StudyFrequencyStats
from digiseg_api.models.study_full import StudyFull
from digiseg_api.models.study_ingestion_status import StudyIngestionStatus
from digiseg_api.models.study_item import StudyItem
from digiseg_api.models.study_lifecycle_stage import StudyLifecycleStage
from digiseg_api.models.study_links import StudyLinks
from digiseg_api.models.study_meta import StudyMeta
from digiseg_api.models.study_mutation import StudyMutation
from digiseg_api.models.study_mutation_data import StudyMutationData
from digiseg_api.models.study_permissions import StudyPermissions
from digiseg_api.models.study_summary_stats import StudySummaryStats
from digiseg_api.models.study_timeline_date import StudyTimelineDate
from digiseg_api.models.study_timeline_hour import StudyTimelineHour
from digiseg_api.models.study_timeline_stats import StudyTimelineStats
from digiseg_api.models.study_timing_stats import StudyTimingStats
from digiseg_api.models.subscription_offer_aux import SubscriptionOfferAux
from digiseg_api.models.subscription_offer_base import SubscriptionOfferBase
from digiseg_api.models.subscription_offer_creation import SubscriptionOfferCreation
from digiseg_api.models.subscription_offer_full import SubscriptionOfferFull
from digiseg_api.models.subscription_offer_item import SubscriptionOfferItem
from digiseg_api.models.subscription_plan_aux import SubscriptionPlanAux
from digiseg_api.models.subscription_plan_base import SubscriptionPlanBase
from digiseg_api.models.subscription_plan_full import SubscriptionPlanFull
from digiseg_api.models.subscription_plan_item import SubscriptionPlanItem
from digiseg_api.models.subscription_plan_mutation import SubscriptionPlanMutation
from digiseg_api.models.subscription_price import SubscriptionPrice
from digiseg_api.models.subscription_price_currency import SubscriptionPriceCurrency
from digiseg_api.models.subscription_price_interval import SubscriptionPriceInterval
from digiseg_api.models.subscription_product_type import SubscriptionProductType
from digiseg_api.models.tax_id import TaxId
from digiseg_api.models.timestamped_object import TimestampedObject
from digiseg_api.models.timestamped_object1 import TimestampedObject1
from digiseg_api.models.user_account_membership import UserAccountMembership
from digiseg_api.models.user_account_membership_base import UserAccountMembershipBase
from digiseg_api.models.user_account_membership_include_aux import UserAccountMembershipIncludeAux
from digiseg_api.models.user_account_membership_update import UserAccountMembershipUpdate
from digiseg_api.models.user_account_role import UserAccountRole
from digiseg_api.models.user_aux import UserAux
from digiseg_api.models.user_base import UserBase
from digiseg_api.models.user_creation import UserCreation
from digiseg_api.models.user_creation_notification import UserCreationNotification
from digiseg_api.models.user_credentials import UserCredentials
from digiseg_api.models.user_full import UserFull
from digiseg_api.models.user_include_param import UserIncludeParam
from digiseg_api.models.user_item import UserItem
from digiseg_api.models.user_links import UserLinks
from digiseg_api.models.user_mutation import UserMutation
from digiseg_api.models.user_platform_role import UserPlatformRole
from digiseg_api.models.user_sort_option import UserSortOption
